package com.pbgis.engine.geometry;

public enum RelationType {
	CROSS, DISJOINT, IN, INTERIOR_INTERSECTION, INTERSECTION, LINE_COINCIDENCE, LINE_TOUCH, OVERLAP, POINT_TOUCH, TOUCH, WITHIN, RELATION
}
